version: '3'

services:
  workspace:
    build:
      context: ./docker/workspace
    volumes:
      - ./:/var/www
    tty: true

  ### APP Utilities ##################################
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
#      - ./docker/app/base/php8.0.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
#      - ./docker/app/base/nginx/local/sites:/etc/nginx/sites-enabled
      - /tmp
    cap_add:
      - SYS_PTRACE
    ports:
      - "9000:9000"

  ### NGINX Server #########################################
  nginx:
    container_name: nginx
    image: registry.cn-hangzhou.aliyuncs.com/mn/laravel-nginx:magento-1.0.0
    volumes:
      - ./:/var/www:cached
      - ./docker/docker-runtime/nginx/log:/var/log/nginx
      - ./docker/nginx/local/sites:/etc/nginx/sites-available
    ports:
      - "8000:80"
      - "8003:8003"
    depends_on:
      - php-fpm
#
#  ### MySQL ################################################
  mysql:
    platform: linux/amd64
    build:
      context: ./docker/mysql
      args:
        - MYSQL_VERSION=latest
    environment:
      - MYSQL_DATABASE=magento_init_db
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - ./docker/docker-runtime/mysql:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "33060:3306"
#
#  ### Redis ################################################
  redis:
    platform: linux/amd64
    image: registry.cn-hangzhou.aliyuncs.com/mn/magento_redis:0.0.1
    volumes:
      - ./docker/docker-runtime/redis:/data
    ports:
      - "6379:6379"
#
#  ## Varnish ##########################################
  varnish:
    platform: linux/amd64
#    image: registry.cn-hangzhou.aliyuncs.com/mn/magento_varnish:0.0.1
    build:
      context: ./docker/varnish
      args:
        - VARNISH_PORT=6081
        - BACKEND_HOST=nginx
        - BACKEND_PORT=8003
        - VARNISHD_PARAMS="-p default_ttl=3600 -p default_grace=3600 -p http_resp_hdr_len=70000 -p http_resp_size=100000"
    ports:
      - "6081:6081"
    volumes:
      - ./docker/varnish/errors:/etc/varnish/errors
#
#  ### ElasticSearch ########################################
  elasticsearch:
    #    platform: linux/amd64
    #    image: registry.cn-hangzhou.aliyuncs.com/mn/magento_elasticsearch:0.0.1
    build:
      context: ./docker/elasticsearch
      args:
        - ELK_VERSION=7.9.1
    volumes:
      - ./docker/elasticsearch:/usr/share/elasticsearch/data
      - ./docker/docker-runtime/elasticsearch:/usr/share/elasticsearch/logs
    environment:
      - cluster.name=laradock-cluster
      - node.name=laradock-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=laradock-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"

  ### Webgrind ##########################################
#  webgrind:
#    image: jokkedk/webgrind:latest
#    volumes_from:
#      - magento_app
#    volumes:
#      - /var/www/html
#    ports:
#      - "8002:80"
#    links:
#      - magento_app