# Changelog(1.0.0):
# - Update docker base image
# - Add prestige backup logic

FROM registry.cn-hangzhou.aliyuncs.com/mn/magento-app:dev-8.0.0

LABEL maintainer="Sophia Wang <sophia.wang@mobilenowgroup.com>"

COPY ./ /var/www

COPY .env.prod /var/www/.env

RUN apt-get update && apt-get install vim -y

WORKDIR /var/www

CMD /opt/startup.sh

EXPOSE 9000 80 81